name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Lint with Ruff
        run: |
          source .venv/bin/activate
          ruff check src/
      - name: Format with Black
        run: |
          source .venv/bin/activate
          black --check src/
      - name: Type check with mypy
        run: |
          source .venv/bin/activate
          mypy src/
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
